title: Kseniia Maksimova
logo: /assets/img/logo.jpg
email: kseniiaguide@gmail.com
description: Native speaking certified teacher of Russian as a foreign language, tourist guide-interpreter
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
